import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

type Locale = 'en' | 'es' | 'fr' | 'de' | 'sl' | 'it';

const translations = {
  en: {
    home_greeting: 'Hello,',
    home_sos: 'SOS',
    home_pulse: 'PULSE',
    home_emergency_help: 'Check\nyour Vitals',
    home_vitals: 'Your Vitals',
    home_heart_rate: 'Heart Rate',
    home_blood_oxygen: 'Blood Oxygen',
    home_respiratory: 'Respiratory',
    home_blood_pressure: 'Blood Pressure',
    medical_title: 'Medical Profile',
    medical_age: 'Age',
    medical_blood_group: 'Blood Group',
    medical_medication: 'Current Medication',
    medical_allergies: 'Known Allergies',
    medical_history: 'Medical History',
    contacts_family: 'Family & Friends',
    contacts_medical: 'Medical Providers',
    contacts_add_family: 'Add family contact',
    contacts_add_medical: 'Add medical provider',
    settings_title: 'Settings',
    settings_privacy: 'Privacy & Emergency',
    settings_share_medical: 'Medical Summary',
    settings_share_location: 'Live Location',
    settings_language: 'Language',
    btn_edit: 'Edit',
    btn_save: 'Save',
    btn_login: 'Sign In',
    btn_signup: 'Sign Up',
    btn_create_account: 'Create Account',
    btn_continue: 'Continue',
    btn_skip: 'Skip',
    btn_get_started: 'Get Started',
    login_title: 'Welcome back',
    login_subtitle: 'Sign in as a patient or responder',
    login_email: 'Email',
    login_password: 'Password',
    login_no_account: 'Do not have an account?',
    signup_title: 'Create account',
    signup_subtitle: 'Create a dedicated patient or responder account',
    signup_name: 'Full Name',
    signup_confirm: 'Confirm Password',
    signup_type: 'Account Type',
    signup_already: 'Already have an account?',
    role_user: 'User',
    role_responder: 'Responder',
    onboarding_welcome: 'Welcome to LifeLine',
    onboarding_hero: 'Be First in Line to Save a Life',
    onboarding_desc: 'Your all-in-one emergency companion. Track vitals, connect to help, and is ready when every second counts.',
    onboarding_1_title: 'Swift Emergency Response',
    onboarding_1_desc: 'Connect with certified responders in your vicinity instantly.',
    onboarding_2_title: 'Integrated Medical Summary',
    onboarding_2_desc: 'Responders get vital medical info the moment they arrive.',
    onboarding_3_title: 'Live Location Tracking',
    onboarding_3_desc: 'Help finds you wherever you are with real-time GPS.',
    spouse: 'Spouse',
    sibling: 'Sibling',
    child: 'Child',
    extended: 'Extended',
    consent_title: 'Privacy Policy',
    consent_subtitle: 'We care about your privacy. Please read and accept the terms before using the application.',
    consent_decline: 'Decline',
    consent_accept: 'Accept',
    consent_scroll: 'Scroll to the bottom to confirm',
    home_ekg: 'ECG',
    home_live: 'Live',
    home_bpm: 'bpm',
    incident_title: 'Active incident',
    incident_stage: 'Search stage',
    incident_responder: 'Assigned responder',
    incident_waiting: 'Waiting for escalation events.',
    btn_cancel_incident: 'Cancel incident',
  },
  es: {
    home_greeting: 'Hola,',
    home_sos: 'SOS',
    home_pulse: 'PULSO',
    home_emergency_help: 'Comprueba\ntus constantes',
    home_vitals: 'Tus signos vitales',
    home_heart_rate: 'Ritmo cardíaco',
    home_blood_oxygen: 'Oxígeno en sangre',
    home_respiratory: 'Respiratorio',
    home_blood_pressure: 'Presión arterial',
    medical_title: 'Perfil médico',
    medical_age: 'Edad',
    medical_blood_group: 'Grupo sanguíneo',
    medical_medication: 'Medicamento actual',
    medical_allergies: 'Alergias conocidas',
    medical_history: 'Historia clínica',
    contacts_family: 'Familiares y amigos',
    contacts_medical: 'Proveedores médicos',
    contacts_add_family: 'Añadir contacto familiar',
    contacts_add_medical: 'Añadir proveedor médico',
    settings_title: 'Ajustes',
    settings_privacy: 'Privacidad y emergencia',
    settings_share_medical: 'Resumen médico',
    settings_share_location: 'Ubicación en vivo',
    settings_language: 'Idioma',
    btn_edit: 'Editar',
    btn_save: 'Guardar',
    btn_login: 'Iniciar sesión',
    btn_signup: 'Registrarse',
    btn_create_account: 'Crear cuenta',
    btn_continue: 'Continuar',
    btn_skip: 'Saltar',
    btn_get_started: 'Empezar',
    login_title: 'Bienvenido de nuevo',
    login_subtitle: 'Inicie sesión como paciente o respondedor',
    login_email: 'Correo electrónico',
    login_password: 'Contraseña',
    login_no_account: '¿No tienes una cuenta?',
    signup_title: 'Crear cuenta',
    signup_subtitle: 'Cree una cuenta dedicada de paciente o respondedor',
    signup_name: 'Nombre completo',
    signup_confirm: 'Confirmar contraseña',
    signup_type: 'Tipo de cuenta',
    signup_already: '¿Ya tienes una cuenta?',
    role_user: 'Usuario',
    role_responder: 'Respondedor',
    onboarding_welcome: 'Bienvenido a LifeLine',
    onboarding_hero: 'Sé el primero en la fila para salvar una vida',
    onboarding_desc: 'Tu compañero de emergencia todo en uno. Controla constantes, conecta con ayuda y está listo cuando cada segundo cuenta.',
    onboarding_1_title: 'Respuesta rápida de emergencia',
    onboarding_1_desc: 'Conéctese con respondedores certificados en su vecindad al instante.',
    onboarding_2_title: 'Resumen médico integrado',
    onboarding_2_desc: 'Los respondedores obtienen información médica vital al llegar.',
    onboarding_3_title: 'Seguimiento de ubicación en vivo',
    onboarding_3_desc: 'La ayuda lo encuentra dondequiera que esté con GPS en tiempo real.',
    spouse: 'Cónyuge',
    sibling: 'Hermano/a',
    child: 'Hijo/a',
    extended: 'Extendido',
    consent_title: 'Política de Privacidad',
    consent_subtitle: 'Nos preocupamos por tu privacidad. Por favor, lee y acepta los términos antes de usar la aplicación.',
    consent_decline: 'Rechazar',
    consent_accept: 'Aceptar',
    consent_scroll: 'Desplázate hasta el final para confirmar',
    home_ekg: 'ECG',
    home_live: 'En vivo',
    home_bpm: 'lpm',
    incident_title: 'Incidente activo',
    incident_stage: 'Etapa de búsqueda',
    incident_responder: 'Respondedor asignado',
    incident_waiting: 'Esperando eventos de escalada.',
    btn_cancel_incident: 'Cancelar incidente',
  },
  fr: {
    home_greeting: 'Bonjour,',
    home_sos: 'SOS',
    home_pulse: 'POULS',
    home_emergency_help: 'Constantes',
    home_vitals: 'Vos constantes',
    home_heart_rate: 'Fréquence cardiaque',
    home_blood_oxygen: 'Oxygène sanguin',
    home_respiratory: 'Respiratoire',
    home_blood_pressure: 'Pression artérielle',
    medical_title: 'Profil médical',
    medical_age: 'Âge',
    medical_blood_group: 'Groupe sanguin',
    medical_medication: 'Médicament actuel',
    medical_allergies: 'Allergies connues',
    medical_history: 'Historique médical',
    contacts_family: 'Famille et amis',
    contacts_medical: 'Fournisseurs médicaux',
    contacts_add_family: 'Ajouter un contact',
    contacts_add_medical: 'Ajouter un médecin',
    settings_title: 'Paramètres',
    settings_privacy: 'Privacité et urgence',
    settings_share_medical: 'Résumé médical',
    settings_share_location: 'Position en direct',
    settings_language: 'Langue',
    btn_edit: 'Modifier',
    btn_save: 'Sauvegarder',
    btn_login: 'Connexion',
    btn_signup: 'Inscription',
    btn_create_account: 'Créer un compte',
    btn_continue: 'Continuer',
    btn_skip: 'Passer',
    btn_get_started: 'Commencer',
    login_title: 'Bon retour',
    login_subtitle: 'Connectez-vous en tant que patient ou secouriste',
    login_email: 'E-mail',
    login_password: 'Mot de passe',
    login_no_account: 'Vous n\'avez pas de compte ?',
    signup_title: 'Créer un compte',
    signup_subtitle: 'Créez un compte patient ou secouriste dédié',
    signup_name: 'Nom complet',
    signup_confirm: 'Confirmer le mot de passe',
    signup_type: 'Type de compte',
    signup_already: 'Vous avez déjà un compte ?',
    role_user: 'Utilisateur',
    role_responder: 'Secouriste',
    onboarding_welcome: 'Bienvenue sur LifeLine',
    onboarding_hero: 'Soyez le premier à sauver une vie',
    onboarding_desc: 'Votre compagnon d\'urgence tout-en-un. Suivez vos constantes, appelez à l\'aide et soyez prêt quand chaque seconde compte.',
    onboarding_1_title: 'Réponse d\'urgence rapide',
    onboarding_1_desc: 'Connectez-vous instantanément avec des secouristes certifiés à proximité.',
    onboarding_2_title: 'Résumé médical intégré',
    onboarding_2_desc: 'Les secouristes reçoivent des infos médicales vitales dès leur arrivée.',
    onboarding_3_title: 'Suivi de position en direct',
    onboarding_3_desc: 'L\'aide vous trouve où que vous soyez grâce au GPS en temps réel.',
    spouse: 'Conjoint',
    sibling: 'Frère/Sœur',
    child: 'Enfant',
    extended: 'Étendue',
    consent_title: 'Politique de Confidentialité',
    consent_subtitle: 'Nous nous soucions de votre vie privée. Veuillez lire et accepter les termes avant d\'utiliser l\'application.',
    consent_decline: 'Refuser',
    consent_accept: 'Accepter',
    consent_scroll: 'Faites défiler vers le bas pour confirmer',
    home_ekg: 'ECG',
    home_live: 'Direct',
    home_bpm: 'bpm',
    incident_title: 'Incident actif',
    incident_stage: 'Étape de recherche',
    incident_responder: 'Secouriste assigné',
    incident_waiting: 'En attente d\'événements d\'escalade.',
    btn_cancel_incident: 'Annuler l\'incident',
  },
  de: {
    home_greeting: 'Hallo,',
    home_sos: 'SOS',
    home_pulse: 'PULS',
    home_emergency_help: 'Überprüfen Sie\nIhre Vitalwerte',
    home_vitals: 'Ihre Vitalwerte',
    home_heart_rate: 'Herzfrequenz',
    home_blood_oxygen: 'Blutsauerstoff',
    home_respiratory: 'Atmung',
    home_blood_pressure: 'Blutdruck',
    medical_title: 'Medizinisches Profil',
    medical_age: 'Alter',
    medical_blood_group: 'Blutgruppe',
    medical_medication: 'Aktuelle Medikation',
    medical_allergies: 'Bekannte Allergien',
    medical_history: 'Krankengeschichte',
    contacts_family: 'Familie & Freunde',
    contacts_medical: 'Medizinische Betreuer',
    contacts_add_family: 'Familienkontakt hinzufügen',
    contacts_add_medical: 'Betreuer hinzufügen',
    settings_title: 'Einstellungen',
    settings_privacy: 'Datenschutz & Notfall',
    settings_share_medical: 'Medizinische Info',
    settings_share_location: 'Standort teilen',
    settings_language: 'Sprache',
    btn_edit: 'Bearbeiten',
    btn_save: 'Speichern',
    btn_login: 'Anmelden',
    btn_signup: 'Registrieren',
    btn_create_account: 'Konto erstellen',
    btn_continue: 'Weiter',
    btn_skip: 'Überspringen',
    btn_get_started: 'Loslegen',
    login_title: 'Willkommen zurück',
    login_subtitle: 'Melden Sie sich als Patient oder Ersthelfer an',
    login_email: 'E-Mail',
    login_password: 'Passwort',
    login_no_account: 'Haben Sie noch kein Konto?',
    signup_title: 'Konto erstellen',
    signup_subtitle: 'Erstellen Sie ein Patienten- oder Ersthelferkonto',
    signup_name: 'Vollständiger Name',
    signup_confirm: 'Passwort bestätigen',
    signup_type: 'Kontotyp',
    signup_already: 'Haben Sie bereits ein Konto?',
    role_user: 'Benutzer',
    role_responder: 'Ersthelfer',
    onboarding_welcome: 'Willkommen bei LifeLine',
    onboarding_hero: 'Seien Sie der Erste, der ein Leben rettet',
    onboarding_desc: 'Ihr All-in-One-Notfallbegleiter. Vitalwerte verfolgen, Hilfe rufen und bereit sein, wenn jede Sekunde zählt.',
    onboarding_1_title: 'Schnelle Notfallhilfe',
    onboarding_1_desc: 'Verbinden Sie sich sofort mit zertifizierten Ersthelfern in Ihrer Nähe.',
    onboarding_2_title: 'Integrierte medizinische Info',
    onboarding_2_desc: 'Ersthelfer erhalten wichtige medizinische Infos bei der Ankunft.',
    onboarding_3_title: 'Live-Standortverfolgung',
    onboarding_3_desc: 'Hilfe findet Sie überall dank Echtzeit-GPS.',
    spouse: 'Ehepartner',
    sibling: 'Geschwister',
    child: 'Kind',
    extended: 'Erweitert',
    consent_title: 'Datenschutzerklärung',
    consent_subtitle: 'Ihre Privatsphäre ist uns wichtig. Bitte lesen und akzeptieren Sie die Bedingungen, bevor Sie die Anwendung nutzen.',
    consent_decline: 'Ablehnen',
    consent_accept: 'Akzeptieren',
    consent_scroll: 'Zum Bestätigen nach unten scrollen',
    home_ekg: 'ECG',
    home_live: 'Live',
    home_bpm: 'bpm',
    incident_title: 'Aktiver Vorfall',
    incident_stage: 'Suchphase',
    incident_responder: 'Zugewiesener Helfer',
    incident_waiting: 'Warten auf Eskalationsereignisse.',
    btn_cancel_incident: 'Vorfall abbrechen',
  },
  sl: {
    home_greeting: 'Živijo,',
    home_sos: 'SOS',
    home_pulse: 'UTRIP',
    home_emergency_help: 'Preverite\nvitalne znake',
    home_vitals: 'Vaši vitalni znaki',
    home_heart_rate: 'Srčni utrip',
    home_blood_oxygen: 'Kisik v krvi',
    home_respiratory: 'Dihanje',
    home_blood_pressure: 'Krvni tlak',
    medical_title: 'Medicinski profil',
    medical_age: 'Starost',
    medical_blood_group: 'Krvna skupina',
    medical_medication: 'Trenutna zdravila',
    medical_allergies: 'Znanje alergije',
    medical_history: 'Medicinska zgodovina',
    contacts_family: 'Družina in prijatelji',
    contacts_medical: 'Zdravstveni delavci',
    contacts_add_family: 'Dodaj stik',
    contacts_add_medical: 'Dodaj zdravnika',
    settings_title: 'Nastavitve',
    settings_privacy: 'Zasebnost in nujni primeri',
    settings_share_medical: 'Povzetek podatkov',
    settings_share_location: 'Lokacija v živo',
    settings_language: 'Jezik',
    btn_edit: 'Uredi',
    btn_save: 'Shrani',
    btn_login: 'Prijava',
    btn_signup: 'Registracija',
    btn_create_account: 'Ustvari račun',
    btn_continue: 'Nadaljuj',
    btn_skip: 'Preskoči',
    btn_get_started: 'Začni',
    login_title: 'Dobrodošli nazaj',
    login_subtitle: 'Prijavite se kot pacient ali reševalec',
    login_email: 'E-pošta',
    login_password: 'Geslo',
    login_no_account: 'Še nimate računa?',
    signup_title: 'Ustvari račun',
    signup_subtitle: 'Ustvarite namenski račun za pacienta ali reševalca',
    signup_name: 'Polno ime',
    signup_confirm: 'Potrdi geslo',
    signup_type: 'Vrsta računa',
    signup_already: 'Že imate račun?',
    role_user: 'Uporabnik',
    role_responder: 'Reševalec',
    onboarding_welcome: 'Dobrodošli v LifeLine',
    onboarding_hero: 'Bodite prvi v vrsti, da rešite življenje',
    onboarding_desc: 'Vaš vsestranski spremljevalec v nujnih primerih. Spremljajte vitalne znake, pokličite pomoč in bodite pripravljeni, ko šteje vsaka sekunda.',
    onboarding_1_title: 'Hiter nujni odziv',
    onboarding_1_desc: 'Takoj se povežite s pooblaščenimi reševalci v vaši bližini.',
    onboarding_2_title: 'Integriran medicinski povzetek',
    onboarding_2_desc: 'Reševalci ob prihodu prejmejo ključne zdravstvene podatke.',
    onboarding_3_title: 'Spremljanje lokacije v živo',
    onboarding_3_desc: 'Pomoč vas najde kjerkoli s pomočjo GPS-a v realnem času.',
    spouse: 'Partner',
    sibling: 'Brat/Sestra',
    child: 'Otrok',
    extended: 'Širše',
    consent_title: 'Pravilnik o Zasebnosti',
    consent_subtitle: 'Skrbimo za vašo zasebnost. Pred uporabo aplikacije preberite in sprejmite pogoje.',
    consent_decline: 'Zavrni',
    consent_accept: 'Sprejmi',
    consent_scroll: 'Pomaknite se do dna za potrditev',
    home_ekg: 'ECG',
    home_live: 'V živo',
    home_bpm: 'utripov',
    incident_title: 'Aktiven incident',
    incident_stage: 'Stopnja iskanja',
    incident_responder: 'Dodeljen reševalec',
    incident_waiting: 'Čakanje na dogodke stopnjevanja.',
    btn_cancel_incident: 'Prekliči incident',
  },
  it: {
    home_greeting: 'Ciao,',
    home_sos: 'SOS',
    home_pulse: 'PULSAZIONE',
    home_emergency_help: 'Controlla i\ntuoi parametri vitali',
    home_vitals: 'I tuoi parametri vitali',
    home_heart_rate: 'Battito cardiaco',
    home_blood_oxygen: 'Ossigeno nel sangue',
    home_respiratory: 'Respirazione',
    home_blood_pressure: 'Pressione sanguigna',
    medical_title: 'Profilo Medico',
    medical_age: 'Età',
    medical_blood_group: 'Gruppo Sanguigno',
    medical_medication: 'Farmaci attuali',
    medical_allergies: 'Allergie note',
    medical_history: 'Storia medica',
    contacts_family: 'Famiglia e Amici',
    contacts_medical: 'Fornitori medici',
    contacts_add_family: 'Aggiungi contatto familiare',
    contacts_add_medical: 'Aggiungi fornitore medico',
    settings_title: 'Impostazioni',
    settings_privacy: 'Privacy ed Emergenza',
    settings_share_medical: 'Sommario Medico',
    settings_share_location: 'Posizione in tempo reale',
    settings_language: 'Lingua',
    btn_edit: 'Modifica',
    btn_save: 'Salva',
    btn_login: 'Accedi',
    btn_signup: 'Iscriviti',
    btn_create_account: 'Crea account',
    btn_continue: 'Continua',
    btn_skip: 'Salta',
    btn_get_started: 'Inizia',
    login_title: 'Bentornato',
    login_subtitle: 'Accedi come paziente o soccorritore',
    login_email: 'E-mail',
    login_password: 'Password',
    login_no_account: 'Non hai un account?',
    signup_title: 'Crea account',
    signup_subtitle: 'Crea un account dedicato paziente o soccorritore',
    signup_name: 'Nome completo',
    signup_confirm: 'Conferma password',
    signup_type: 'Tipo di account',
    signup_already: 'Hai già un account?',
    role_user: 'Utente',
    role_responder: 'Soccorritore',
    onboarding_welcome: 'Benvenuti in LifeLine',
    onboarding_hero: 'Sii il primo in linea per salvare una vita',
    onboarding_desc: 'Il tuo compagno di emergenza tutto in uno. Monitora i parametri vitali, chiedi aiuto e sii pronto quando ogni secondo conta.',
    onboarding_1_title: 'Risposta rapida alle emergenze',
    onboarding_1_desc: 'Connettiti istantaneamente con soccorritori certificati nelle vicinanze.',
    onboarding_2_title: 'Sommario medico integrato',
    onboarding_2_desc: 'I soccorritori ricevono info mediche vitali al loro arrivo.',
    onboarding_3_title: 'Localizzazione GPS dal vivo',
    onboarding_3_desc: 'L\'aiuto ti trova ovunque tu sia grazie al GPS in tempo reale.',
    spouse: 'Coniuge',
    sibling: 'Fratello/Sorella',
    child: 'Figlio/a',
    extended: 'Esteso',
    consent_title: 'Informativa sulla Privacy',
    consent_subtitle: 'Ci prendiamo cura della tua privacy. Leggi e accetta i termini prima di utilizzare l\'applicazione.',
    consent_decline: 'Rifiuta',
    consent_accept: 'Accetta',
    consent_scroll: 'Scorri fino in fondo per confermare',
    home_ekg: 'ECG',
    home_live: 'Dal vivo',
    home_bpm: 'bpm',
    incident_title: 'Incidente attivo',
    incident_stage: 'Fase di ricerca',
    incident_responder: 'Soccorritore assegnato',
    incident_waiting: 'In attesa di eventi di escalation.',
    btn_cancel_incident: 'Annulla incidente',
  }
};

type LocalizationContextType = {
  t: (key: keyof typeof translations['en']) => string;
  locale: Locale;
  setLocale: (locale: Locale) => void;
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>('en');

  useEffect(() => {
    const loadLocale = async () => {
      const savedLocale = await AsyncStorage.getItem('app_locale');
      if (savedLocale && savedLocale in translations) {
        setLocaleState(savedLocale as Locale);
      }
    };
    loadLocale();
  }, []);

  const setLocale = async (newLocale: Locale) => {
    setLocaleState(newLocale);
    await AsyncStorage.getItem('app_locale'); // Just a check
    await AsyncStorage.setItem('app_locale', newLocale);
  };

  const t = (key: keyof typeof translations['en']) => {
    return translations[locale][key] || translations['en'][key];
  };

  return (
    <LocalizationContext.Provider value={{ t, locale, setLocale }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};
