import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

type Locale = 'en' | 'es' | 'fr' | 'de' | 'sl' | 'it';

const translations = {
  en: {
    home_greeting: 'Hello,',
    home_sos: 'SOS',
    home_pulse: 'PULSE',
    home_emergency_help: 'Check\nyour Vitals',
    home_vitals: 'Your Vitals',
    home_heart_rate: 'Heart Rate',
    home_blood_oxygen: 'Blood Oxygen',
    home_respiratory: 'Respiratory',
    home_blood_pressure: 'Blood Pressure',
    medical_title: 'Medical Profile',
    medical_age: 'Age',
    medical_blood_group: 'Blood Group',
    medical_medication: 'Current Medication',
    medical_allergies: 'Known Allergies',
    medical_history: 'Medical History',
    contacts_family: 'Family & Friends',
    contacts_medical: 'Medical Providers',
    contacts_add_family: 'Add family contact',
    contacts_add_medical: 'Add medical provider',
    settings_title: 'Settings',
    settings_privacy: 'Privacy & Emergency',
    settings_share_medical: 'Medical Summary',
    settings_share_location: 'Live Location',
    settings_language: 'Language',
    btn_edit: 'Edit',
    btn_save: 'Save',
    btn_login: 'Sign In',
    btn_signup: 'Sign Up',
    btn_create_account: 'Create Account',
    btn_continue: 'Continue',
    btn_skip: 'Skip',
    btn_get_started: 'Get Started',
    login_title: 'Welcome back',
    login_subtitle: 'Sign in as a patient or responder',
    login_email: 'Email',
    login_password: 'Password',
    login_no_account: 'Do not have an account?',
    signup_title: 'Create account',
    signup_subtitle: 'Create a dedicated patient or responder account',
    signup_name: 'Full Name',
    signup_confirm: 'Confirm Password',
    signup_type: 'Account Type',
    signup_already: 'Already have an account?',
    role_user: 'User',
    role_responder: 'Responder',
    onboarding_welcome: 'Welcome to LifeLine',
    onboarding_hero: 'Be First in Line to Save a Life',
    onboarding_desc: 'Your all-in-one emergency companion. Track vitals, connect to help, and is ready when every second counts.',
    onboarding_1_title: 'Swift Emergency Response',
    onboarding_1_desc: 'Connect with certified responders in your vicinity instantly.',
    onboarding_2_title: 'Integrated Medical Summary',
    onboarding_2_desc: 'Responders get vital medical info the moment they arrive.',
    onboarding_3_title: 'Live Location Tracking',
    onboarding_3_desc: 'Help finds you wherever you are with real-time GPS.',
    spouse: 'Spouse',
    sibling: 'Sibling',
    child: 'Child',
    extended: 'Extended',
    consent_title: 'Privacy Policy',
    consent_subtitle: 'We care about your privacy. Please read and accept the terms before using the application.',
    consent_decline: 'Decline',
    consent_accept: 'Accept',
    consent_scroll: 'Scroll to the bottom to confirm',
    home_ekg: 'ECG',
    home_live: 'Live',
    home_bpm: 'bpm',
    incident_title: 'Active incident',
    incident_stage: 'Search stage',
    incident_responder: 'Assigned responder',
    incident_waiting: 'Waiting for escalation events.',
    btn_cancel_incident: 'Cancel incident',
    settings_logout: 'Log Out',
    settings_logout_desc: 'Safely sign out of your session',
    settings_logout_confirm_title: 'Log Out',
    settings_logout_confirm_desc: 'Are you sure you want to log out of your account?',
    btn_cancel: 'Cancel',
    btn_logout: 'Log Out',
    responder_greeting: '{{name}},',
    responder_headline: 'Save a\nlife today.',
    resp_available: 'AVAILABLE',
    resp_unavailable: 'UNAVAILABLE',
    resp_live_dispatch: 'Live Dispatch',
    resp_verification_pending: 'Verification Pending',
    resp_travel_mode_desc: 'Your travel mode ensures accurate ETA for alerts.',
    resp_availability_status: 'Availability Status',
    resp_walking: 'Walking',
    resp_driving: 'Driving',
    resp_verification_title: 'Responder verification',
    resp_verified_desc: 'Verified and eligible for dispatch',
    resp_rejected_desc: 'Needs updated credential submission',
    resp_pending_desc: 'Submit credentials to unlock dispatching',
    resp_placeholder_qualification: 'EMT, doctor, nurse, CPR-certified volunteer',
    resp_placeholder_cert: 'License or certificate number',
    resp_placeholder_notes: 'Optional notes for the operations team',
    resp_btn_submit: 'Submit verification',
    resp_btn_approve_demo: 'Approve for demo',
    resp_assigned_incident: 'Assigned incident',
    resp_btn_backup: 'Request backup',
    resp_btn_arrived: 'Arrived',
    resp_btn_complete: 'Complete',
    resp_incoming_alerts: 'Incoming alerts',
    resp_no_alerts: 'No active alerts',
    resp_no_alerts_desc: 'Keep availability on to receive the next incident.',
    resp_emergency_summary: 'Emergency summary',
    resp_blood_group: 'Blood group',
    resp_allergies: 'Allergies',
    resp_conditions: 'Conditions',
    resp_medications: 'Medications',
    resp_decline: 'Decline',
    resp_accept: 'Accept',
    resp_unknown: 'Unknown',
    resp_none: 'None listed',
    home_sos_subtext: 'Deep press to activate!',
    guidance_eyebrow: 'Guided response',
    guidance_title: 'What happens in the first minute',
    guidance_step_1: 'Call 144 and confirm the exact floor or entrance for responders.',
    guidance_step_2: 'Start CPR immediately if the patient is unresponsive and not breathing normally.',
    guidance_step_3: 'Send one person to look for an AED while another stays with the patient.',
    guidance_risk_elevated: 'Elevated',
    guidance_risk_stable: 'Stable',
    guidance_footer_label: 'Wearable trigger',
    guidance_footer_body: 'Simulate an automatic emergency escalation with live vitals attached.',
    guidance_btn_sending: 'Sending...',
    guidance_btn_simulate: 'Simulate',
  },
  es: {
    home_greeting: 'Hola,',
    home_sos: 'SOS',
    home_pulse: 'PULSO',
    home_emergency_help: 'Comprueba\ntus constantes',
    home_vitals: 'Tus signos vitales',
    home_heart_rate: 'Ritmo cardíaco',
    home_blood_oxygen: 'Oxígeno en sangre',
    home_respiratory: 'Respiratorio',
    home_blood_pressure: 'Presión arterial',
    medical_title: 'Perfil médico',
    medical_age: 'Edad',
    medical_blood_group: 'Grupo sanguíneo',
    medical_medication: 'Medicamento actual',
    medical_allergies: 'Alergias conocidas',
    medical_history: 'Historia clínica',
    contacts_family: 'Familiares y amigos',
    contacts_medical: 'Proveedores médicos',
    contacts_add_family: 'Añadir contacto familiar',
    contacts_add_medical: 'Añadir proveedor médico',
    settings_title: 'Ajustes',
    settings_privacy: 'Privacidad y emergencia',
    settings_share_medical: 'Resumen médico',
    settings_share_location: 'Ubicación en vivo',
    settings_language: 'Idioma',
    btn_edit: 'Editar',
    btn_save: 'Guardar',
    btn_login: 'Iniciar sesión',
    btn_signup: 'Registrarse',
    btn_create_account: 'Crear cuenta',
    btn_continue: 'Continuar',
    btn_skip: 'Saltar',
    btn_get_started: 'Empezar',
    login_title: 'Bienvenido de nuevo',
    login_subtitle: 'Inicie sesión como paciente o respondedor',
    login_email: 'Correo electrónico',
    login_password: 'Contraseña',
    login_no_account: '¿No tienes una cuenta?',
    signup_title: 'Crear cuenta',
    signup_subtitle: 'Cree una cuenta dedicada de paciente o respondedor',
    signup_name: 'Nombre completo',
    signup_confirm: 'Confirmar contraseña',
    signup_type: 'Tipo de cuenta',
    signup_already: '¿Ya tienes una cuenta?',
    role_user: 'Usuario',
    role_responder: 'Respondedor',
    onboarding_welcome: 'Bienvenido a LifeLine',
    onboarding_hero: 'Sé el primero en la fila para salvar una vida',
    onboarding_desc: 'Tu compañero de emergencia todo en uno. Controla constantes, conecta con ayuda y está listo cuando cada segundo cuenta.',
    onboarding_1_title: 'Respuesta rápida de emergencia',
    onboarding_1_desc: 'Conéctese con respondedores certificados en su vecindad al instante.',
    onboarding_2_title: 'Resumen médico integrado',
    onboarding_2_desc: 'Los respondedores obtienen información médica vital al llegar.',
    onboarding_3_title: 'Seguimiento de ubicación en vivo',
    onboarding_3_desc: 'La ayuda lo encuentra dondequiera que esté con GPS en tiempo real.',
    spouse: 'Cónyuge',
    sibling: 'Hermano/a',
    child: 'Hijo/a',
    extended: 'Extendido',
    consent_title: 'Política de Privacidad',
    consent_subtitle: 'Nos preocupamos por tu privacidad. Por favor, lee y acepta los términos antes de usar la aplicación.',
    consent_decline: 'Rechazar',
    consent_accept: 'Aceptar',
    consent_scroll: 'Desplázate hasta el final para confirmar',
    home_ekg: 'ECG',
    home_live: 'En vivo',
    home_bpm: 'lpm',
    incident_title: 'Incidente activo',
    incident_stage: 'Etapa de búsqueda',
    incident_responder: 'Respondedor asignado',
    incident_waiting: 'Esperando eventos de escalada.',
    btn_cancel_incident: 'Cancelar incidente',
    settings_logout: 'Cerrar sesión',
    settings_logout_desc: 'Cierre su sesión de forma segura',
    settings_logout_confirm_title: 'Cerrar sesión',
    settings_logout_confirm_desc: '¿Está seguro de que desea cerrar la sesión de su cuenta?',
    btn_cancel: 'Cancelar',
    btn_logout: 'Cerrar sesión',
    responder_greeting: '{{name}},',
    responder_headline: 'Salva una\nvida hoy.',
    resp_available: 'DISPONIBLE',
    resp_unavailable: 'NO DISPONIBLE',
    resp_live_dispatch: 'Despacho en vivo',
    resp_verification_pending: 'Verificación pendiente',
    resp_travel_mode_desc: 'Tu modo de viaje asegura un ETA preciso para alertas.',
    resp_availability_status: 'Estado de disponibilidad',
    resp_walking: 'Caminando',
    resp_driving: 'Conduciendo',
    resp_verification_title: 'Verificación de respondedor',
    resp_verified_desc: 'Verificado y elegible para el despacho',
    resp_rejected_desc: 'Necesita una actualización de credenciales',
    resp_pending_desc: 'Envía credenciales para desbloquear el despacho',
    resp_placeholder_qualification: 'EMT, médico, enfermero, voluntario certificado en RCP',
    resp_placeholder_cert: 'Número de licencia o certificado',
    resp_placeholder_notes: 'Notas opcionales para el equipo de operaciones',
    resp_btn_submit: 'Enviar verificación',
    resp_btn_approve_demo: 'Aprobar para demo',
    resp_assigned_incident: 'Incidente asignado',
    resp_btn_backup: 'Solicitar refuerzos',
    resp_btn_arrived: 'Llegado',
    resp_btn_complete: 'Completado',
    resp_incoming_alerts: 'Alertas entrantes',
    resp_no_alerts: 'Sin alertas activas',
    resp_no_alerts_desc: 'Mantén la disponibilidad activada para recibir incidentes.',
    resp_emergency_summary: 'Resumen de emergencia',
    resp_blood_group: 'Grupo sanguíneo',
    resp_allergies: 'Alergias',
    resp_conditions: 'Condiciones',
    resp_medications: 'Medicamentos',
    resp_decline: 'Rechazar',
    resp_accept: 'Aceptar',
    resp_unknown: 'Desconocido',
    resp_none: 'Ninguno listado',
    home_sos_subtext: '¡Presiona fuerte para activar!',
    guidance_eyebrow: 'Respuesta guiada',
    guidance_title: 'Qué pasa en el primer minuto',
    guidance_step_1: 'Llama al 144 y confirma el piso o entrada exacta para los respondedores.',
    guidance_step_2: 'Inicia la RCP inmediatamente si el paciente no responde y no respira normalmente.',
    guidance_step_3: 'Envía a una persona a buscar un DEA mientras otra se queda con el paciente.',
    guidance_risk_elevated: 'Elevado',
    guidance_risk_stable: 'Estable',
    guidance_footer_label: 'Activador de wearable',
    guidance_footer_body: 'Simula una escalada de emergencia automática con signos vitales adjuntos.',
    guidance_btn_sending: 'Enviando...',
    guidance_btn_simulate: 'Simular',
  },
  fr: {
    home_greeting: 'Bonjour,',
    home_sos: 'SOS',
    home_pulse: 'POULS',
    home_emergency_help: 'Constantes',
    home_vitals: 'Vos constantes',
    home_heart_rate: 'Fréquence cardiaque',
    home_blood_oxygen: 'Oxygène sanguin',
    home_respiratory: 'Respiratoire',
    home_blood_pressure: 'Pression artérielle',
    medical_title: 'Profil médical',
    medical_age: 'Âge',
    medical_blood_group: 'Groupe sanguin',
    medical_medication: 'Médicament actuel',
    medical_allergies: 'Allergies connues',
    medical_history: 'Historique médical',
    contacts_family: 'Famille et amis',
    contacts_medical: 'Fournisseurs médicaux',
    contacts_add_family: 'Ajouter un contact',
    contacts_add_medical: 'Ajouter un médecin',
    settings_title: 'Paramètres',
    settings_privacy: 'Privacité et urgence',
    settings_share_medical: 'Résumé médical',
    settings_share_location: 'Position en direct',
    settings_language: 'Langue',
    btn_edit: 'Modifier',
    btn_save: 'Sauvegarder',
    btn_login: 'Connexion',
    btn_signup: 'Inscription',
    btn_create_account: 'Créer un compte',
    btn_continue: 'Continuer',
    btn_skip: 'Passer',
    btn_get_started: 'Commencer',
    login_title: 'Bon retour',
    login_subtitle: 'Connectez-vous en tant que patient ou secouriste',
    login_email: 'E-mail',
    login_password: 'Mot de passe',
    login_no_account: 'Vous n\'avez pas de compte ?',
    signup_title: 'Créer un compte',
    signup_subtitle: 'Créez un compte patient ou secouriste dédié',
    signup_name: 'Nom complet',
    signup_confirm: 'Confirmer le mot de passe',
    signup_type: 'Type de compte',
    signup_already: 'Vous avez déjà un compte ?',
    role_user: 'Utilisateur',
    role_responder: 'Secouriste',
    onboarding_welcome: 'Bienvenue sur LifeLine',
    onboarding_hero: 'Soyez le premier à sauver une vie',
    onboarding_desc: 'Votre compagnon d\'urgence tout-en-un. Suivez vos constantes, appelez à l\'aide et soyez prêt quand chaque seconde compte.',
    onboarding_1_title: 'Réponse d\'urgence rapide',
    onboarding_1_desc: 'Connectez-vous instantanément avec des secouristes certifiés à proximité.',
    onboarding_2_title: 'Résumé médical intégré',
    onboarding_2_desc: 'Les secouristes reçoivent des infos médicales vitales dès leur arrivée.',
    onboarding_3_title: 'Suivi de position en direct',
    onboarding_3_desc: 'L\'aide vous trouve où que vous soyez grâce au GPS en temps réel.',
    spouse: 'Conjoint',
    sibling: 'Frère/Sœur',
    child: 'Enfant',
    extended: 'Étendue',
    consent_title: 'Politique de Confidentialité',
    consent_subtitle: 'Nous nous soucions de votre vie privée. Veuillez lire et accepter les termes avant d\'utiliser l\'application.',
    consent_decline: 'Refuser',
    consent_accept: 'Accepter',
    consent_scroll: 'Faites défiler vers le bas pour confirmer',
    home_ekg: 'ECG',
    home_live: 'Direct',
    home_bpm: 'bpm',
    incident_title: 'Incident actif',
    incident_stage: 'Étape de recherche',
    incident_responder: 'Secouriste assigné',
    incident_waiting: 'En attente d\'événements d\'escalade.',
    btn_cancel_incident: 'Annuler l\'incident',
    settings_logout: 'Déconnexion',
    settings_logout_desc: 'Déconnectez-vous en toute sécurité',
    settings_logout_confirm_title: 'Déconnexion',
    settings_logout_confirm_desc: 'Êtes-vous sûr de vouloir vous déconnecter de votre compte ?',
    btn_cancel: 'Annuler',
    btn_logout: 'Déconnexion',
    responder_greeting: '{{name}},',
    responder_headline: 'Sauvez una\nvie aujourd\'hui.',
    resp_available: 'DISPONIBLE',
    resp_unavailable: 'INDISPONIBLE',
    resp_live_dispatch: 'Répartition en direct',
    resp_verification_pending: 'Vérification en attente',
    resp_travel_mode_desc: 'Votre mode de transport assure un ETA précis.',
    resp_availability_status: 'Statut de disponibilité',
    resp_walking: 'À pied',
    resp_driving: 'En voiture',
    resp_verification_title: 'Vérification du répondant',
    resp_verified_desc: 'Vérifié et éligible pour la répartition',
    resp_rejected_desc: 'Nécessite une mise à jour des informations',
    resp_pending_desc: 'Soumettez vos informations pour débloquer la répartition',
    resp_placeholder_qualification: 'EMT, médecin, infirmier, bénévole certifié RCP',
    resp_placeholder_cert: 'Numéro de licence ou de certificat',
    resp_placeholder_notes: 'Notes facultatives pour l\'équipe des opérations',
    resp_btn_submit: 'Soumettre la vérification',
    resp_btn_approve_demo: 'Approuver pour la démo',
    resp_assigned_incident: 'Incident assigné',
    resp_btn_backup: 'Demander du renfort',
    resp_btn_arrived: 'Arrivé',
    resp_btn_complete: 'Terminé',
    resp_incoming_alerts: 'Alertes entrantes',
    resp_no_alerts: 'Aucune alerte active',
    resp_no_alerts_desc: 'Restez disponible pour recevoir le prochain incident.',
    resp_emergency_summary: 'Résumé d\'urgence',
    resp_blood_group: 'Groupe sanguin',
    resp_allergies: 'Allergies',
    resp_conditions: 'Conditions',
    resp_medications: 'Médicaments',
    resp_decline: 'Décliner',
    resp_accept: 'Accepter',
    resp_unknown: 'Inconnu',
    resp_none: 'Aucun listé',
    home_sos_subtext: 'Appuyez fort pour activer !',
    guidance_eyebrow: 'Réponse guidée',
    guidance_title: 'Ce qui se passe la première minute',
    guidance_step_1: 'Appelez le 144 et confirmez l\'étage ou l\'entrée exact pour les secours.',
    guidance_step_2: 'Commencez la RCR immédiatement si le patient ne répond pas et ne respire pas normalement.',
    guidance_step_3: 'Envoyez quelqu\'un chercher un DAE pendant qu\'un autre reste avec le patient.',
    guidance_risk_elevated: 'Élevé',
    guidance_risk_stable: 'Stable',
    guidance_footer_label: 'Déclencheur portable',
    guidance_footer_body: 'Simulez une escalade automatique d\'urgence avec des paramètres vitaux joints.',
    guidance_btn_sending: 'Envoi...',
    guidance_btn_simulate: 'Simuler',
  },
  de: {
    home_greeting: 'Hallo,',
    home_sos: 'SOS',
    home_pulse: 'PULS',
    home_emergency_help: 'Überprüfen Sie\nIhre Vitalwerte',
    home_vitals: 'Ihre Vitalwerte',
    home_heart_rate: 'Herzfrequenz',
    home_blood_oxygen: 'Blutsauerstoff',
    home_respiratory: 'Atmung',
    home_blood_pressure: 'Blutdruck',
    medical_title: 'Medizinisches Profil',
    medical_age: 'Alter',
    medical_blood_group: 'Blutgruppe',
    medical_medication: 'Aktuelle Medikation',
    medical_allergies: 'Bekannte Allergien',
    medical_history: 'Krankengeschichte',
    contacts_family: 'Familie & Freunde',
    contacts_medical: 'Medizinische Betreuer',
    contacts_add_family: 'Familienkontakt hinzufügen',
    contacts_add_medical: 'Betreuer hinzufügen',
    settings_title: 'Einstellungen',
    settings_privacy: 'Datenschutz & Notfall',
    settings_share_medical: 'Medizinische Info',
    settings_share_location: 'Standort teilen',
    settings_language: 'Sprache',
    btn_edit: 'Bearbeiten',
    btn_save: 'Speichern',
    btn_login: 'Anmelden',
    btn_signup: 'Registrieren',
    btn_create_account: 'Konto erstellen',
    btn_continue: 'Weiter',
    btn_skip: 'Überspringen',
    btn_get_started: 'Loslegen',
    login_title: 'Willkommen zurück',
    login_subtitle: 'Melden Sie sich als Patient oder Ersthelfer an',
    login_email: 'E-Mail',
    login_password: 'Passwort',
    login_no_account: 'Haben Sie noch kein Konto?',
    signup_title: 'Konto erstellen',
    signup_subtitle: 'Erstellen Sie ein Patienten- oder Ersthelferkonto',
    signup_name: 'Vollständiger Name',
    signup_confirm: 'Passwort bestätigen',
    signup_type: 'Kontotyp',
    signup_already: 'Haben Sie bereits ein Konto?',
    role_user: 'Benutzer',
    role_responder: 'Ersthelfer',
    onboarding_welcome: 'Willkommen bei LifeLine',
    onboarding_hero: 'Seien Sie der Erste, der ein Leben rettet',
    onboarding_desc: 'Ihr All-in-One-Notfallbegleiter. Vitalwerte verfolgen, Hilfe rufen und bereit sein, wenn jede Sekunde zählt.',
    onboarding_1_title: 'Schnelle Notfallhilfe',
    onboarding_1_desc: 'Verbinden Sie sich sofort mit zertifizierten Ersthelfern in Ihrer Nähe.',
    onboarding_2_title: 'Integrierte medizinische Info',
    onboarding_2_desc: 'Ersthelfer erhalten wichtige medizinische Infos bei der Ankunft.',
    onboarding_3_title: 'Live-Standortverfolgung',
    onboarding_3_desc: 'Hilfe findet Sie überall dank Echtzeit-GPS.',
    spouse: 'Ehepartner',
    sibling: 'Geschwister',
    child: 'Kind',
    extended: 'Erweitert',
    consent_title: 'Datenschutzerklärung',
    consent_subtitle: 'Ihre Privatsphäre ist uns wichtig. Bitte lesen und akzeptieren Sie die Bedingungen, bevor Sie die Anwendung nutzen.',
    consent_decline: 'Ablehnen',
    consent_accept: 'Akzeptieren',
    consent_scroll: 'Zum Bestätigen nach unten scrollen',
    home_ekg: 'ECG',
    home_live: 'Live',
    home_bpm: 'bpm',
    incident_title: 'Aktiver Vorfall',
    incident_stage: 'Suchphase',
    incident_responder: 'Zugewiesener Helfer',
    incident_waiting: 'Warten auf Eskalationsereignisse.',
    btn_cancel_incident: 'Vorfall abbrechen',
    settings_logout: 'Abmelden',
    settings_logout_desc: 'Sicher von Ihrer Sitzung abmelden',
    settings_logout_confirm_title: 'Abmelden',
    settings_logout_confirm_desc: 'Sind Sie sicher, dass Sie sich von Ihrem Konto abmelden möchten?',
    btn_cancel: 'Abbrechen',
    btn_logout: 'Abmelden',
    responder_greeting: '{{name}},',
    responder_headline: 'Rette heute\nein Leben.',
    resp_available: 'VERFÜGBAR',
    resp_unavailable: 'NICHT VERFÜGBAR',
    resp_live_dispatch: 'Live-Einsatzleitung',
    resp_verification_pending: 'Verifizierung ausstehend',
    resp_travel_mode_desc: 'Ihr Reisemodus sorgt für eine genaue Ankunftszeit.',
    resp_availability_status: 'Verfügbarkeitsstatus',
    resp_walking: 'Zu Fuß',
    resp_driving: 'Mit dem Auto',
    resp_verification_title: 'Ersthelfer-Verifizierung',
    resp_verified_desc: 'Verifiziert und einsatzbereit',
    resp_rejected_desc: 'Aktualisierte Unterlagen erforderlich',
    resp_pending_desc: 'Unterlagen einreichen, um Einsätze freizuschalten',
    resp_placeholder_qualification: 'Sanitäter, Arzt, Pflegekraft, HLW-zertifiziert',
    resp_placeholder_cert: 'Lizenz- oder Zertifikatsnummer',
    resp_placeholder_notes: 'Optionale Anmerkungen für das Einsatzteam',
    resp_btn_submit: 'Verifizierung einreichen',
    resp_btn_approve_demo: 'Für Demo freigeben',
    resp_assigned_incident: 'Zugewiesener Vorfall',
    resp_btn_backup: 'Verstärkung anfordern',
    resp_btn_arrived: 'Eingetroffen',
    resp_btn_complete: 'Abgeschlossen',
    resp_incoming_alerts: 'Eingehende Alarme',
    resp_no_alerts: 'Keine aktiven Alarme',
    resp_no_alerts_desc: 'Verfügbarkeit aktiviert lassen, um Einsätze zu erhalten.',
    resp_emergency_summary: 'Notfall-Zusammenfassung',
    resp_blood_group: 'Blutgruppe',
    resp_allergies: 'Allergien',
    resp_conditions: 'Erkrankungen',
    resp_medications: 'Medikamente',
    resp_decline: 'Ablehnen',
    resp_accept: 'Annehmen',
    resp_unknown: 'Unbekannt',
    resp_none: 'Keine angegeben',
    home_sos_subtext: 'Fest drücken zum Aktivieren!',
    guidance_eyebrow: 'Geleitete Antwort',
    guidance_title: 'Was in der ersten Minute passiert',
    guidance_step_1: 'Rufen Sie 144 an und bestätigen Sie die genaue Etage oder den Eingang für Ersthelfer.',
    guidance_step_2: 'Beginnen Sie sofort mit HLW, wenn der Patient nicht ansprechbar ist und nicht normal atmet.',
    guidance_step_3: 'Senden Sie eine Person, um einen AED zu suchen, während eine andere beim Patienten bleibt.',
    guidance_risk_elevated: 'Erhöht',
    guidance_risk_stable: 'Stabil',
    guidance_footer_label: 'Wearable-Auslöser',
    guidance_footer_body: 'Simulieren Sie eine automatische Notfalleskalation mit angehängten Vitalwerten.',
    guidance_btn_sending: 'Senden...',
    guidance_btn_simulate: 'Simulieren',
  },
  sl: {
    home_greeting: 'Živijo,',
    home_sos: 'SOS',
    home_pulse: 'UTRIP',
    home_emergency_help: 'Preverite\nvitalne znake',
    home_vitals: 'Vaši vitalni znaki',
    home_heart_rate: 'Srčni utrip',
    home_blood_oxygen: 'Kisik v krvi',
    home_respiratory: 'Dihanje',
    home_blood_pressure: 'Krvni tlak',
    medical_title: 'Medicinski profil',
    medical_age: 'Starost',
    medical_blood_group: 'Krvna skupina',
    medical_medication: 'Trenutna zdravila',
    medical_allergies: 'Znanje alergije',
    medical_history: 'Medicinska zgodovina',
    contacts_family: 'Družina in prijatelji',
    contacts_medical: 'Zdravstveni delavci',
    contacts_add_family: 'Dodaj stik',
    contacts_add_medical: 'Dodaj zdravnika',
    settings_title: 'Nastavitve',
    settings_privacy: 'Zasebnost in nujni primeri',
    settings_share_medical: 'Povzetek podatkov',
    settings_share_location: 'Lokacija v živo',
    settings_language: 'Jezik',
    btn_edit: 'Uredi',
    btn_save: 'Shrani',
    btn_login: 'Prijava',
    btn_signup: 'Registracija',
    btn_create_account: 'Ustvari račun',
    btn_continue: 'Nadaljuj',
    btn_skip: 'Preskoči',
    btn_get_started: 'Začni',
    login_title: 'Dobrodošli nazaj',
    login_subtitle: 'Prijavite se kot pacient ali reševalec',
    login_email: 'E-pošta',
    login_password: 'Geslo',
    login_no_account: 'Še nimate računa?',
    signup_title: 'Ustvari račun',
    signup_subtitle: 'Ustvarite namenski račun za pacienta ali reševalca',
    signup_name: 'Polno ime',
    signup_confirm: 'Potrdi geslo',
    signup_type: 'Vrsta računa',
    signup_already: 'Že imate račun?',
    role_user: 'Uporabnik',
    role_responder: 'Reševalec',
    onboarding_welcome: 'Dobrodošli v LifeLine',
    onboarding_hero: 'Bodite prvi v vrsti, da rešite življenje',
    onboarding_desc: 'Vaš vsestranski spremljevalec v nujnih primerih. Spremljajte vitalne znake, pokličite pomoč in bodite pripravljeni, ko šteje vsaka sekunda.',
    onboarding_1_title: 'Hiter nujni odziv',
    onboarding_1_desc: 'Takoj se povežite s pooblaščenimi reševalci v vaši bližini.',
    onboarding_2_title: 'Integriran medicinski povzetek',
    onboarding_2_desc: 'Reševalci ob prihodu prejmejo ključne zdravstvene podatke.',
    onboarding_3_title: 'Spremljanje lokacije v živo',
    onboarding_3_desc: 'Pomoč vas najde kjerkoli s pomočjo GPS-a v realnem času.',
    spouse: 'Partner',
    sibling: 'Brat/Sestra',
    child: 'Otrok',
    extended: 'Širše',
    consent_title: 'Pravilnik o Zasebnosti',
    consent_subtitle: 'Skrbimo za vašo zasebnost. Pred uporabo aplikacije preberite in sprejmite pogoje.',
    consent_decline: 'Zavrni',
    consent_accept: 'Sprejmi',
    consent_scroll: 'Pomaknite se do dna za potrditev',
    home_ekg: 'ECG',
    home_live: 'V živo',
    home_bpm: 'utripov',
    incident_title: 'Aktiven incident',
    incident_stage: 'Stopnja iskanja',
    incident_responder: 'Dodeljen reševalec',
    incident_waiting: 'Čakanje na dogodke stopnjevanja.',
    btn_cancel_incident: 'Prekliči incident',
    settings_logout: 'Odjava',
    settings_logout_desc: 'Varna odjava iz vaše seje',
    settings_logout_confirm_title: 'Odjava',
    settings_logout_confirm_desc: 'Ali ste prepričani, da se želite odjaviti iz svojega računa?',
    btn_cancel: 'Prekliči',
    btn_logout: 'Odjava',
    responder_greeting: '{{name}},',
    responder_headline: 'Danes reši\nživljenje.',
    resp_available: 'NA VOLJO',
    resp_unavailable: 'NI NA VOLJO',
    resp_live_dispatch: 'Napotitev v živo',
    resp_verification_pending: 'Preverjanje v teku',
    resp_travel_mode_desc: 'Vaš način potovanja zagotavlja natančen čas prihoda.',
    resp_availability_status: 'Status razpoložljivosti',
    resp_walking: 'Peš',
    resp_driving: 'Z avtom',
    resp_verification_title: 'Preverjanje odzivnika',
    resp_verified_desc: 'Preverjeno in pripravljeno za napotitev',
    resp_rejected_desc: 'Potrebna posodobitev dokumentacije',
    resp_pending_desc: 'Pošljite dokumentacijo za odklepanje napotitev',
    resp_placeholder_qualification: 'Reševalec, zdravnik, medicinska sestra, prostovoljec s CPR',
    resp_placeholder_cert: 'Številka licence ali certifikata',
    resp_placeholder_notes: 'Izbirne opombe za operativno ekipo',
    resp_btn_submit: 'Oddaj preverjanje',
    resp_btn_approve_demo: 'Potrdi za demo',
    resp_assigned_incident: 'Dodeljen incident',
    resp_btn_backup: 'Zahtevaj pomoč',
    resp_btn_arrived: 'Na lokaciji',
    resp_btn_complete: 'Zaključeno',
    resp_incoming_alerts: 'Prejeta obvestila',
    resp_no_alerts: 'Ni aktivnih obvestil',
    resp_no_alerts_desc: 'Ostanite na voljo za prejemanje naslednjega incidenta.',
    resp_emergency_summary: 'Povzetek nujnih primerov',
    resp_blood_group: 'Krvna skupina',
    resp_allergies: 'Alergije',
    resp_conditions: 'Stanja',
    resp_medications: 'Zdravila',
    resp_decline: 'Zavrni',
    resp_accept: 'Sprejmi',
    resp_unknown: 'Neznano',
    resp_none: 'Ni navedeno',
    home_sos_subtext: 'Močno pritisnite za aktivacijo!',
    guidance_eyebrow: 'Voden odziv',
    guidance_title: 'Kaj se zgodi v prvi minuti',
    guidance_step_1: 'Pokličite 144 in potrdite točno nadstropje ali vhod za reševalce.',
    guidance_step_2: 'Takoj začnite s TPO, če se pacient ne odziva in ne diha normalno.',
    guidance_step_3: 'Eno osebo pošljite po AED, medtem ko druga ostane s pacientom.',
    guidance_risk_elevated: 'Povišano',
    guidance_risk_stable: 'Stabilno',
    guidance_footer_label: 'Sprožilec nosljive naprave',
    guidance_footer_body: 'Simulirajte samodejno stopnjevanje nujnega primera s priloženimi vitalnimi znaki.',
    guidance_btn_sending: 'Pošiljanje...',
    guidance_btn_simulate: 'Simuliraj',
  },
  it: {
    home_greeting: 'Ciao,',
    home_sos: 'SOS',
    home_pulse: 'PULSAZIONE',
    home_emergency_help: 'Controlla i\ntuoi parametri vitali',
    home_vitals: 'I tuoi parametri vitali',
    home_heart_rate: 'Battito cardiaco',
    home_blood_oxygen: 'Ossigeno nel sangue',
    home_respiratory: 'Respirazione',
    home_blood_pressure: 'Pressione sanguigna',
    medical_title: 'Profilo Medico',
    medical_age: 'Età',
    medical_blood_group: 'Gruppo Sanguigno',
    medical_medication: 'Farmaci attuali',
    medical_allergies: 'Allergie note',
    medical_history: 'Storia medica',
    contacts_family: 'Famiglia e Amici',
    contacts_medical: 'Fornitori medici',
    contacts_add_family: 'Aggiungi contatto familiare',
    contacts_add_medical: 'Aggiungi fornitore medico',
    settings_title: 'Impostazioni',
    settings_privacy: 'Privacy ed Emergenza',
    settings_share_medical: 'Sommario Medico',
    settings_share_location: 'Posizione in tempo reale',
    settings_language: 'Lingua',
    btn_edit: 'Modifica',
    btn_save: 'Salva',
    btn_login: 'Accedi',
    btn_signup: 'Iscriviti',
    btn_create_account: 'Crea account',
    btn_continue: 'Continua',
    btn_skip: 'Salta',
    btn_get_started: 'Inizia',
    login_title: 'Bentornato',
    login_subtitle: 'Accedi come paziente o soccorritore',
    login_email: 'E-mail',
    login_password: 'Password',
    login_no_account: 'Non hai un account?',
    signup_title: 'Crea account',
    signup_subtitle: 'Crea un account dedicato paziente o soccorritore',
    signup_name: 'Nome completo',
    signup_confirm: 'Conferma password',
    signup_type: 'Tipo di account',
    signup_already: 'Hai già un account?',
    role_user: 'Utente',
    role_responder: 'Soccorritore',
    onboarding_welcome: 'Benvenuti in LifeLine',
    onboarding_hero: 'Sii il primo in linea per salvare una vita',
    onboarding_desc: 'Il tuo compagno di emergenza tutto in uno. Monitora i parametri vitali, chiedi aiuto e sii pronto quando ogni secondo conta.',
    onboarding_1_title: 'Risposta rapida alle emergenze',
    onboarding_1_desc: 'Connettiti istantaneamente con soccorritori certificati nelle vicinanze.',
    onboarding_2_title: 'Sommario medico integrato',
    onboarding_2_desc: 'I soccorritori ricevono info mediche vitali al loro arrivo.',
    onboarding_3_title: 'Localizzazione GPS dal vivo',
    onboarding_3_desc: 'L\'aiuto ti trova ovunque tu sia grazie al GPS in tempo reale.',
    spouse: 'Coniuge',
    sibling: 'Fratello/Sorella',
    child: 'Figlio/a',
    extended: 'Esteso',
    consent_title: 'Informativa sulla Privacy',
    consent_subtitle: 'Ci prendiamo cura della tua privacy. Leggi e accetta i termini prima di utilizzare l\'applicazione.',
    consent_decline: 'Rifiuta',
    consent_accept: 'Accetta',
    consent_scroll: 'Scorri fino in fondo per confermare',
    home_ekg: 'ECG',
    home_live: 'Dal vivo',
    home_bpm: 'bpm',
    incident_title: 'Incidente attivo',
    incident_stage: 'Fase di ricerca',
    incident_responder: 'Soccorritore assegnato',
    incident_waiting: 'In attesa di eventi di escalation.',
    btn_cancel_incident: 'Annulla incidente',
    settings_logout: 'Disconnetti',
    settings_logout_desc: 'Esci in sicurezza dalla tua sessione',
    settings_logout_confirm_title: 'Disconnetti',
    settings_logout_confirm_desc: 'Sei sicuro di voler uscire dal tuo account?',
    btn_cancel: 'Annulla',
    btn_logout: 'Disconnetti',
    responder_greeting: '{{name}},',
    responder_headline: 'Salva una\nvita oggi.',
    resp_available: 'DISPONIBILE',
    resp_unavailable: 'NON DISPONIBILE',
    resp_live_dispatch: 'Centrale operativa',
    resp_verification_pending: 'Verifica in corso',
    resp_travel_mode_desc: 'La modalità di viaggio assicura un ETA preciso.',
    resp_availability_status: 'Stato disponibilità',
    resp_walking: 'A piedi',
    resp_driving: 'In auto',
    resp_verification_title: 'Verifica soccorritore',
    resp_verified_desc: 'Verificato ed idoneo all\'intervento',
    resp_rejected_desc: 'Necessario aggiornamento credenziali',
    resp_pending_desc: 'Invia credenziali per sbloccare gli interventi',
    resp_placeholder_qualification: 'EMT, medico, infermiere, volontario certificato CPR',
    resp_placeholder_cert: 'Numero di licenza o certificato',
    resp_placeholder_notes: 'Note opzionali per il team operativo',
    resp_btn_submit: 'Invia verifica',
    resp_btn_approve_demo: 'Approva per demo',
    resp_assigned_incident: 'Incidente assegnato',
    resp_btn_backup: 'Richiedi rinforzi',
    resp_btn_arrived: 'Arrivato',
    resp_btn_complete: 'Completato',
    resp_incoming_alerts: 'Avvisi in entrata',
    resp_no_alerts: 'Nessun avviso attivo',
    resp_no_alerts_desc: 'Resta disponibile per ricevere il prossimo intervento.',
    resp_emergency_summary: 'Riepilogo emergenza',
    resp_blood_group: 'Gruppo sanguigno',
    resp_allergies: 'Allergie',
    resp_conditions: 'Patologie',
    resp_medications: 'Farmaci',
    resp_decline: 'Rifiuta',
    resp_accept: 'Accetta',
    resp_unknown: 'Sconosciuto',
    resp_none: 'Nessuno indicato',
    home_sos_subtext: 'Premi a fondo per attivare!',
    guidance_eyebrow: 'Risposta guidata',
    guidance_title: 'Cosa succede nel primo minuto',
    guidance_step_1: 'Chiama il 144 e conferma il piano o l\'ingresso esatto per i soccorritori.',
    guidance_step_2: 'Inizia subito la RCP se il paziente non reagisce e non respira normalmente.',
    guidance_step_3: 'Invia una persona a cercare un DAE mentre un\'altra rimane con il paziente.',
    guidance_risk_elevated: 'Elevato',
    guidance_risk_stable: 'Stabile',
    guidance_footer_label: 'Attivatore wearable',
    guidance_footer_body: 'Simula un\'escalation di emergenza automatica con parametri vitali allegati.',
    guidance_btn_sending: 'Invio...',
    guidance_btn_simulate: 'Simula',
  },
};

type LocalizationContextType = {
  t: (key: keyof typeof translations['en'], params?: Record<string, string>) => string;
  locale: Locale;
  setLocale: (locale: Locale) => void;
};

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>('en');

  useEffect(() => {
    const loadLocale = async () => {
      const savedLocale = await AsyncStorage.getItem('app_locale');
      if (savedLocale && savedLocale in translations) {
        setLocaleState(savedLocale as Locale);
      }
    };
    loadLocale();
  }, []);

  const setLocale = async (newLocale: Locale) => {
    setLocaleState(newLocale);
    await AsyncStorage.getItem('app_locale'); // Just a check
    await AsyncStorage.setItem('app_locale', newLocale);
  };

  const t = (key: keyof typeof translations['en'], params?: Record<string, string>) => {
    let text = translations[locale][key] || translations['en'][key] || '';
    if (params) {
      Object.keys(params).forEach((param) => {
        text = text.replace(`{{${param}}}`, params[param]);
      });
    }
    return text;
  };

  return (
    <LocalizationContext.Provider value={{ t, locale, setLocale }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};
